COMMON_FLAGS="-O3 -pipe -march=znver2 --param=l1-cache-line-size=64 --param=l1-cache-size=32 --param=l2-cache-size=512 -flto=auto -fgraphite-identity -floop-nest-optimize -fdevirtualize-at-ltrans -fipa-pta -fno-semantic-interposition -fuse-linker-plugin"

CFLAGS="${COMMON_FLAGS}"
CXXFLAGS="${COMMON_FLAGS}"
FCFLAGS="${COMMON_FLAGS}"
FFLAGS="${COMMON_FLAGS}"
LDFLAGS="-Wl,-O3 -Wl,--as-needed -Wl,-z,pack-relative-relocs ${COMMON_FLAGS}"

CGO_CFLAGS="${COMMON_FLAGS}"
CGO_CXXFLAGS="${COMMON_FLAGS}"
CGO_FCFLAGS="${COMMON_FLAGS}"
CGO_FFLAGS="${COMMON_FLAGS}"
CGO_LDFLAGS="-Wl,-O3 -Wl,--as-needed -Wl,-z,pack-relative-relocs ${COMMON_FLAGS}"


RUSTFLAGS="${RUSTFLAGS} -C target-cpu=native -C opt-level=3 -C debuginfo=0 -C strip=symbols"


USE="-aqua -selinux -apparmor -cups -clamav -connman -coreaudio -cuda -emacs -geoip -geolocation -gnome-keyring -ieee1394 -ios -ipod -keyring -lirc -nntp -nvenc -pcmcia \
	-speech -vnc -xemacs -ibm -3dfx -cjk -jack -smartcard -policykit -gstreamer -consolekit -kerberos -ldap -wayland -webkit -webengine -kde -gnome -xfce -pulseaudio \
	-bluetooth -vlc -networkmanager -udisks -systemd -pam -elogind -dbus -accessibility -libnotify -startup-notification -pipewire -automount -trash-panel-plugin -pcre -gvfs \
	-dbusmenu -qt -gtk -qt5 -qt6 -gpm -initramfs -introspection -tiff -telemetry -gnome-shell -proprietary-codecs -vala -gmp-autoupdate -wxwidgets -nvidia -emboss -bindist \
	-deno -discord -dhcp -soc -udev -qdbus -screencast -assistant -debug -debuginfod -test -ipv6 -icu -sanitize -perl -verify-sig -kmod \
    \
    X minimal ssl vaapi vulkan savedconfig pgo custom-cflags"


FEATURES="parallel-install parallel-fetch usersync"

MAKEOPTS="-j32 -l32"
EMERGE_DEFAULT_OPTS="--with-bdeps y --quiet-build --verbose --verbose-conflicts --keep-going y"

VIDEO_CARDS="amdgpu radeonsi radeon"

L10N="en-GB"

PORTDIR=/var/db/repos/gentoo

QEMU_USER_TARGETS="x86_64"
QEMU_SOFTMMU_TARGETS="x86_64"

ACCEPT_LICENSE="-* @FREE"

LC_MESSAGES=C.UTF-8

CPU_FLAGS_X86="aes avx avx2 bmi1 bmi2 f16c fma3 mmx mmxext pclmul popcnt rdrand sha sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3"
